// <auto-generated />
using System;
using AMMS.Hanet.Datas.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMMS.Hanet.Datas.Migrations.MySQL
{
    [DbContext(typeof(DeviceAutoPushDbContext))]
    partial class DeviceAutoPushDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Hanet")
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AMMS.Hanet.Datas.Entities.hanet_terminal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("area_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("change_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("change_user")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("create_user")
                        .HasColumnType("longtext");

                    b.Property<int?>("face_count")
                        .HasColumnType("int");

                    b.Property<int?>("fv_count")
                        .HasColumnType("int");

                    b.Property<string>("ip_address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("last_activity")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("port")
                        .HasColumnType("int");

                    b.Property<DateTime?>("push_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("sn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("upload_time")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("user_count")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("terminal", "Hanet");
                });
#pragma warning restore 612, 618
        }
    }
}
